rm "./epstein_files_project_final_v2/qdrant_embed_chunks.py"
rm "./vector_db_bootstrap.sh"
rm "./epstein_files_pipeline.py"
rm "./epstein_files_project_final (2)/epstein_files_pipeline.py"
rm "./epstein_files_project_final/epstein_files_pipeline.py"
rm "./epstein_files_project_final_v2 (2)/epstein_files_pipeline.py"
rm "./epstein_files_project_final_v2/epstein_files_pipeline.py"
rm "./epstein_files_project_final/cbw_bootstrap_project_ubuntu.sh"
rm "./epstein_files_project_final_v2 (2)/cbw_bootstrap_project_ubuntu.sh"
rm "./epstein_files_project_final_v2/cbw_bootstrap_project_ubuntu.sh"
rm "./epstein_files_download_ocr_ner_pipeline_python_optional_ts.py"
rm "./epstein_files_project_final_v2 (2)/vector_db_bootstrap.sh"
rm "./epstein_files_project_final_v2/vector_db_bootstrap.sh"
rm "./epstein_files_project_final/vector_db_bootstrap.sh"
rm "./vector_db_bootstrap_sh_v_2_qdrant_postgres_pgvector_findings_schema.sh"
rm "./epstein_files_project_final/scripts/doctor.py"
rm "./epstein_files_project_final_v2 (2)/scripts/doctor.py"
rm "./epstein_files_project_final_v2/scripts/doctor.py"
rm "./epstein_files_project_final_v2/qdrant_semantic_search.py"
rm "./epstein_files_project_final (2)/db_ingest_artifacts.py"
rm "./epstein_files_project_final/db_ingest_artifacts.py"
rm "./epstein_files_project_final_v2 (2)/db_ingest_artifacts.py"
rm "./epstein_files_project_final_v2/db_ingest_artifacts.py"
